POST https://localhost:5001/Hotel/produto/cadastro
Content-Type: application/json

{
    "Nome" : "suco"
}

### Deletar cliente pelo CPF
DELETE https://localhost:5001/hotel/produto/delete/

### Alterar os dados do cliente
PUT https://localhost:5001/hotel/produto/alterar

###consultar dados do cliente
GET https://localhost:5001/hotel/cliente/consulta

###lista de cliente cadastradco no hotel
GET https://localhost:5001/hotel/produto/lista