### Cadastrar um novo produto
POST https://localhost:5001/api/produto/create
Content-Type: application/json

{
    "Nome" : "Quarto 1",
    "Preco" : 3.5,
    "Disponivel": 1,
    "Descricao" : "Imagine uma descrição aqui",
    "CategoriaId" : 1
}

### Listar todos os produtos
GET https://localhost:5001/api/quarto/list

### Buscar um produto pelo id
GET https://localhost:5001/api/quarto/getbyid/1

### Deletar um produto pelo nome
DELETE https://localhost:5001/api/quarto/delete/Quarto_1

### Alterar um produto
PUT https://localhost:5001/api/quarto/update
Content-Type: application/json

{
    "Id" : 1,
    "Nome" : "Quarto alterada",
    "Preco" : 3.5
}
