POST https://localhost:5001/hotel/produto/cadastro
Content-Type: application/json

{
    "Nome" : "João"
}

### Deletar produto pelo CPF
DELETE https://localhost:5001/hotel/produto/delete/

### Alterar os dados do produto
PUT https://localhost:5001/hotel/produto/alterar

###consultar dados do produto
GET https://localhost:5001/hotel/produto/consulta

###lista de produto cadastradco no hotel
GET https://localhost:5001/hotel/produto/lista