### Cadastrar cliente
POST https://localhost:5001/hotel/reserva/create
Content-Type: application/json

{
    "Cpf" : 321,
    "Nome" : "Silvana",
    "quarto" : 30,
    "Valor" : 2000
}

### Listar clientes
GET https://localhost:5001/hotel/reserva/list

### Deletar cliente pelo cpf
DELETE https://localhost:5001/hotel/reserva/delete/321

